[tool.poetry]
name = "flarenet"
version = "0.1.1"
description = "a convolutional neural network to predict flares in 20-second TESS data"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
lksearch = ">=1.2.1" 
numpy = ">=2.3.2"
tensorflow = "^2.20.0"



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"



